# run: conda env create --file environment.yml
# run: conda env create python=3.6 --file environment.yml
# include new packages: conda env update --file environment.yml
name: neumo
channels:
  - defaults
dependencies:
  - python=3.6
  - numpy>=1.19
  - pytest>=3.0,<3.8
  - pytest-cov
  - networkx
  - matplotlib
  - pip
  - pip:
    - black
